# Generated by Django 3.2.4 on 2022-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogm',
            name='titulo',
            field=models.CharField(max_length=140),
        ),
    ]
