# Generated by Django 3.2.4 on 2022-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_alter_blogm_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogm',
            name='imagen',
            field=models.ImageField(blank=True, default='img/logo.jpg', null=True, upload_to='blogs'),
        ),
    ]
