# Generated by Django 3.2.4 on 2022-06-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appempresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasm',
            name='imagenempresa',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='empresa', verbose_name='Imagen de la empresa'),
        ),
    ]
