# Generated by Django 3.2.4 on 2022-05-12 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcategorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventosm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloevento', models.CharField(max_length=120)),
                ('contenidoevento', models.TextField()),
                ('imagenevento', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='eventos')),
                ('eventolink', models.CharField(max_length=140)),
                ('fechaevento', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autorevento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventosm', to=settings.AUTH_USER_MODEL)),
                ('categoriaevento', models.ManyToManyField(related_name='categoriasevento', to='appcategorias.categorias')),
            ],
            options={
                'verbose_name': 'eventosm',
                'verbose_name_plural': 'eventosms',
                'ordering': ['-created'],
            },
        ),
    ]
