# Generated by Django 3.2.4 on 2022-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosm',
            name='imagenevento',
            field=models.ImageField(blank=True, default='apprein/img/logo.jpg', null=True, upload_to='eventos'),
        ),
    ]
