# Generated by Django 3.2.4 on 2022-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeventos', '0002_alter_eventosm_imagenevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosm',
            name='fechaevento',
            field=models.DateTimeField(),
        ),
    ]
