# Generated by Django 3.2.4 on 2022-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprein', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagenperfil',
            field=models.ImageField(blank=True, default='perfil/userdefault.jpg', null=True, upload_to='perfil'),
        ),
    ]
