# Generated by Django 3.2.4 on 2022-07-28 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appempresas', '0001_initial'),
        ('apprein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puesto_cargo',
            field=models.CharField(default=0, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombreempesauser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombreempresauser', to='appempresas.empresasm', verbose_name='Elija la empresa:'),
        ),
    ]
