# Generated by Django 3.2.4 on 2022-05-26 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcategorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloforo', models.CharField(max_length=50, verbose_name='Titulo del foro:')),
                ('contenidoforo', models.TextField(verbose_name='Descripción del foro:')),
                ('imagenforo', models.ImageField(default='img/logo.jpg', upload_to='foro', verbose_name='Imagen del foro:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autorforo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foroms', to=settings.AUTH_USER_MODEL, verbose_name='Autor del foro:')),
                ('categoriasforo', models.ManyToManyField(related_name='categoriasforo', to='appcategorias.categorias', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'forom',
                'verbose_name_plural': 'foroms',
                'ordering': ['-created'],
            },
        ),
    ]
