# Generated by Django 3.2.4 on 2022-03-29 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_forom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria_forom',
                'verbose_name_plural': 'categoria_foroms',
            },
        ),
        migrations.CreateModel(
            name='forom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(default='logo.jpg', upload_to='foro')),
                ('like', models.IntegerField(default=0)),
                ('nolike', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('autorf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foroms', to=settings.AUTH_USER_MODEL)),
                ('categoriasforo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appforo.categoria_forom')),
            ],
            options={
                'verbose_name': 'forom',
                'verbose_name_plural': 'foroms',
                'ordering': ['-created'],
            },
        ),
    ]
