# Generated by Django 3.2.4 on 2022-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appforo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forom',
            options={'verbose_name': 'forom', 'verbose_name_plural': 'foroms'},
        ),
    ]
