# Generated by Django 3.2.4 on 2022-04-01 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentariosblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosblogm',
            name='autorcoment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.user'),
            preserve_default=False,
        ),
    ]
